const EXPENSES = {
  LOAD: "LOAD_EXPENSES",
  LOAD_SUCCESS: "LOAD_EXPENSES_SUCCESS",
  LOAD_FAIL: "LOAD_EXPENSES_FAIL",
};

const USER = {
  LOAD: "LOAD_USER",
  LOAD_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_FAIL: "LOAD_USER_FAIL",
};

export { EXPENSES, USER };
